Refactor php 7.4
nextcloud/recommendations pull request #513
Opened 2022-04-26 10:56 UTC by CarlSchwan

2022-05-05 15:28 UTC, come-nc approved these changes

2022-05-09 09:03 UTC, nickvergessen requested changes
Installing fails on 7.4

2022-05-09 09:03 UTC, nickvergessen commented on .github/workflows/test.yml
> +        run: if ${{ needs.oci.result != 'success' and needs.sqlite.result != 'success' and needs.mysql.result != 'success' and needs.pgsql.result != 'success'}}; then exit 1; fi
Invalid workflow file: .github/workflows/test.yml#L268
The workflow is not valid. .github/workflows/test.yml (Line: 268, Col: 14): Unexpected symbol: 'and'. Located at position 31 within expression: needs.oci

2022-05-09 09:24 UTC, CarlSchwan commented
> Installing fails on 7.4

works for me with both 7.4 and 8.1 locally

2022-05-09 18:44 UTC, ChristophWurst commented
> @ChristophWurst I ended up updating composer and the ci jobs. The list of required ci checks needs to be changed in the github setting.

You have permission to adjust the requried checks :v:

2022-05-09 18:45 UTC, ChristophWurst approved these changes

2022-05-09 18:58 UTC, nickvergessen approved these changes

2022-05-09 18:58 UTC, merged