switch index to ocs
nextcloud/recommendations pull request #829
Opened 2024-12-12 07:45 UTC by tobiasKaminsky

Fix #828 

:rotating_light: webfrontend generates url with "index.php" and thus does not work.

2024-12-12 07:52 UTC, ChristophWurst requested changes
Dear @tobiasKaminsky,
Thank you very much for the contribution.

This seems to convert the internal API of the app to a public API. To meet the standards of a public API, there has to be documentation about it in the developer documentation of Nextcloud. There are two options for an OCS documentation
1. Manually document the endpoints.
2. Use the OpenAPI generator to auto-generate a machine-readable metadata file.

Please note that once the API is public, it can no longer change in breaking ways for one year.

2024-12-12 08:00 UTC, ChristophWurst commented
Please also see https://github.com/nextcloud/recommendations/pull/458. I think the two PRs have the same goal.

2024-12-12 08:40 UTC, nickvergessen commented on src/service/RecommendationService.js
>  import { generateUrl } from '@nextcloud/router'
```suggestion
import { generateOcsUrl } from '@nextcloud/router'
```

2024-12-12 08:40 UTC, nickvergessen commented on src/service/RecommendationService.js
> +	const url = generateUrl('/ocs/v2.php/apps/recommendations/api/v1/recommendations' + (always ? '/always' : ''),
```suggestion
	const url = generateOcsUrl('/apps/recommendations/api/v1/recommendations' + (always ? '/always' : ''),
```

2024-12-12 08:43 UTC, tobiasKaminsky commented on src/service/RecommendationService.js
>  import { generateUrl } from '@nextcloud/router'
:heart: I already did it locally.

2024-12-17 11:56 UTC, provokateurin commented
While you're on this anyway, how about adding https://github.com/nextcloud/openapi-extractor support?
Given the small API surface it shouldn't take much time, but I can also do that for you if you want.

2024-12-18 06:35 UTC, tobiasKaminsky commented
> Given the small API surface it shouldn't take much time, but I can also do that for you if you want.

That would be wonderful :blue_heart:

2024-12-19 07:48 UTC, provokateurin commented
I tried to keep the changes as minimal as possible. Another good cleanup would be to migrate the annotations and routes to attributes.

2024-12-19 07:51 UTC, provokateurin commented
Meh more things to fix

2024-12-19 08:05 UTC, provokateurin commented
OCI test fails are unrelated, the container image that is used no longer works.
Maintainers should switch to the phpunit templates from the org.

2024-12-19 08:36 UTC, ChristophWurst commented
Does this API match https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-recommendations-api.html? These docs were merged prematurely before the integration of https://github.com/nextcloud/recommendations/pull/458.

2025-01-07 15:10 UTC, provokateurin commented
/compile

2025-01-07 23:48 UTC, Pytal approved these changes

2025-01-07 23:54 UTC, merged